import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { Navbar } from "../components/Navbar";
import { trpc } from "../utils/trpc";
import { useEffect } from "react";
import { useMutation } from "react-query";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const tokenMutation = trpc.useMutation(['token.refresh-token'])

  useEffect(() => {
    if (session?.error === "RefreshAccessTokenError") {
      signIn(); // Force sign in to hopefully resolve error
      tokenMutation.mutate()
    }
  }, [session,tokenMutation]);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="dark:bg-gray-800 min-h-screen"></main>
    </>
  );
};

export default Home;
