import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { Navbar } from "../components/Navbar";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery([
    "example.hello",
    { text: "hello from fikri fadillah" },
  ]);
  const name = trpc.useQuery(["example.name", { text: "fikri", age: 12 }]);
  const data = useSession()
  console.log(data)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className="dark:bg-gray-800 min-h-screen">
     </main>
    </>
  );
};

export default Home;
